# Items that cannot be crafted
blocked-items:
  - NETHERITE_UPGRADE_SMITHING_TEMPLATE
  - NETHERITE_AXE
  - NETHERITE_PICKAXE
  - NETHERITE_SHOVEL
  - NETHERITE_HOE
  - NETHERITE_SWORD
  - NETHERITE_HELMET
  - NETHERITE_CHESTPLATE
  - NETHERITE_LEGGINGS
  - NETHERITE_BOOTS
  - NETHERITE_BLOCK

# Items players cannot USE, EQUIP, HOLD, or ATTACK with
banned-use:
  - NETHERITE_AXE
  - NETHERITE_PICKAXE
  - NETHERITE_SHOVEL
  - NETHERITE_HOE
  - NETHERITE_SWORD
  - NETHERITE_HELMET
  - NETHERITE_CHESTPLATE
  - NETHERITE_LEGGINGS
  - NETHERITE_BOOTS
